databaseType = "PostgreSql"
name = "pyconza23-demo"
id = "338f79c9-9cbd-48ea-a223-248b26ccfce0"

[flywayDesktop]
developmentEnvironment = "development"
shadowEnvironment = "shadow"
schemaModel = "./schema-model"

[redgateCompare]
filterFile = "filter.rgf"

[flyway]
mixed = true
outOfOrder = true
locations = [ "filesystem:migrations" ]
validateMigrationNaming = true

[environments.demo]
url = "jdbc:postgresql://localhost:5432/demo"
user = "postgres"
password = "postgres"
schemas = [ "public" ]
displayName = "pyconza23-demo"
